pipeline:
  name: Build gosample
  identifier: Build_moez_ak_gosample_1727777810307
  projectIdentifier: moez_lavji
  orgIdentifier: gft_sandbox_organization
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  identifier: build_go_app
                  name: Build Go App
                  spec:
                    command: |-
                      echo "Welcome to Harness CI"
                      go build
                      go test
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github
        repoName: moez-ak/gosample
        build: <+input>
